# Generated by Django 4.0.1 on 2023-03-30 05:57

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('photo', models.ImageField(upload_to='blog/')),
                ('postby', models.CharField(default='Admin', max_length=50)),
                ('poston', models.DateField(default=datetime.date(2023, 3, 30))),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mrp', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roomno', models.CharField(default='', max_length=20)),
                ('photo', models.ImageField(upload_to='blog/')),
                ('typeofbed', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='', max_length=50)),
                ('noofbeds', models.CharField(default='', max_length=100)),
                ('Rating', models.CharField(default='', max_length=20)),
                ('Isavailableroom', models.CharField(default='Yes', max_length=20)),
                ('roomtype', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Super', 'Super')], default='', max_length=50)),
            ],
            options={
                'db_table': 'Room',
            },
        ),
    ]
