# Generated by Django 4.0.1 on 2023-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_alter_blog_poston'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.IntegerField()),
                ('checkout', models.DateTimeField()),
                ('checkin', models.DateTimeField()),
                ('roomno', models.IntegerField()),
                ('customerid', models.IntegerField()),
                ('brackfast', models.CharField(max_length=50)),
                ('roomtype', models.CharField(choices=[('Deluxe', 'Deluxe'), ('Super', 'Super')], default='', max_length=50)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
