# Generated by Django 4.0.1 on 2023-04-18 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Roomno',
            new_name='Roomtitle',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 18)),
        ),
        migrations.AlterField(
            model_name='room',
            name='Isavailableroom',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
