# Generated by Django 4.0.1 on 2023-04-18 05:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_roomno_room_roomtitle_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
