# Generated by Django 4.0.1 on 2023-04-25 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_room_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='brackfast',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roomno',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registertime',
        ),
        migrations.AddField(
            model_name='booking',
            name='emailid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='noofadults',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='noofchildren',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 4, 25)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='roomtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.room'),
        ),
    ]
