# Generated by Django 4.0.1 on 2023-05-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_room_phot1_room_photo2_alter_blog_poston'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo3',
            field=models.ImageField(default='', upload_to='blog/'),
        ),
    ]
